services:
  database:
    container_name: esv-database
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./database/sql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_USER=paul
      - MYSQL_PASSWORD=genesis
      - MYSQL_DATABASE=bible_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pr00t"]
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      - bible_network
      
  esv-api:
    build: ./api
    ports: 
      - 8080:8080
    depends_on: 
      database:
        condition: service_healthy
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=esv_consumer
      - DB_PASSWORD=esv!
      - DB_PORT=3306
      - DB_NAME=bible_db
      - PORT=8080
      - ESV_API_KEY=${ESV_API_KEY}
    networks:
      - bible_network


  database-tests:
    build: ./tests/database
    container_name: database-tests
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./tests/database:/usr/src/database-tests
    environment:
      - DB_USERNAME=esv_consumer
      - DB_PASSWORD=esv!
      - DB_NAME=bible_db
    networks:
      - bible_network
    command: tail -f /dev/null

  api-tests:
    container_name: api-tests
    build: ./tests/api
    volumes:
      - ./tests/api:/usr/src/api-tests
    environment:
      - API_URL=http://esv-api:8080
    networks:
      - bible_network
    command: tail -F anything

networks:
  bible_network: